server:
  servlet:
    context-path: /imghome
  port: 8083

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    username: root
    password: illya0415
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bootzhong.top:3306/imghome?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC
    #redis
    redis:
      host: bootzhong.top
      port: 6379
      password: illya0415
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0
      timeout: 2000
      database: 0

#mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
